---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by a11.
--- DateTime: 2024/1/29 23:59
---
-- 库存使用量的 key
local stockKey = ARGV[1]
-- 库存总量
local stockCount = tonumber(ARGV[2])

if tonumber(redis.call('get', stockKey)) >= stockCount then
    -- 库存已经用完
    return 0
end
--
local stockUsedCount = redis.call('incrby', stockKey, 1)
return stockUsedCount